[option]
indent = 4
[textrules]
header_copyright = false
style_directives = false
style_semicolon = true
style_textwidth = false
[syntaxrules]
action_block_with_side_effect = true
blocking_assignment_in_always_at_edge = false
blocking_assignment_in_always_ff = false
blocking_assignment_in_always_latch = false
case_default = true
default_nettype_none = false
enum_with_type = true
eventlist_comma_always_ff = false
eventlist_or = true
explicit_case_default = true
explicit_if_else = false
function_same_as_system_function = true
function_with_automatic = true
general_always_level_sensitive = true
general_always_no_edge = false
genvar_declaration_in_loop = false
genvar_declaration_out_loop = true
inout_with_tri = true
input_with_var = false
interface_port_with_modport = false
keyword_forbidden_always = false
keyword_forbidden_always_comb = true
keyword_forbidden_always_ff = true
keyword_forbidden_always_latch = true
keyword_forbidden_generate = false
keyword_forbidden_logic = true
keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
keyword_forbidden_wire_reg = false
keyword_required_generate = true
localparam_explicit_type = false
localparam_type_twostate = false
loop_statement_in_always_comb = false
loop_statement_in_always_ff = false
loop_statement_in_always_latch = false
loop_variable_declaration = false
module_ansi_forbidden = false
module_nonansi_forbidden = true
multiline_for_begin = true
multiline_if_begin = true
non_blocking_assignment_in_always_comb = false
non_blocking_assignment_in_always_no_edge = false
operator_case_equality = true
operator_incdec = true
operator_self_assignment = true
output_with_var = false
package_item_not_in_package = true
parameter_default_value = true
parameter_explicit_type = false
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = false
sequential_block_in_always_comb = false
sequential_block_in_always_ff = false
sequential_block_in_always_latch = false
generate_case_with_label = false
generate_for_with_label = false
generate_if_with_label = false
lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false
prefix_inout = false
prefix_input = false
prefix_instance = false
prefix_interface = false
prefix_module = false
prefix_output = false
prefix_package = false
re_forbidden_assert = false
re_forbidden_assert_property = false
re_forbidden_checker = false
re_forbidden_class = false
re_forbidden_function = false
re_forbidden_generateblock = false
re_forbidden_genvar = false
re_forbidden_instance = false
re_forbidden_interface = false
re_forbidden_localparam = false
re_forbidden_modport = false
re_forbidden_module_ansi = false
re_forbidden_module_nonansi = false
re_forbidden_package = false
re_forbidden_parameter = false
re_forbidden_port_inout = false
re_forbidden_port_input = false
re_forbidden_port_interface = false
re_forbidden_port_output = false
re_forbidden_port_ref = false
re_forbidden_program = false
re_forbidden_property = false
re_forbidden_sequence = false
re_forbidden_task = false
re_forbidden_var_class = false
re_forbidden_var_classmethod = false
re_required_assert = false
re_required_assert_property = false
re_required_checker = false
re_required_class = false
re_required_function = false
re_required_generateblock = false
re_required_genvar = false
re_required_instance = false
re_required_interface = false
re_required_localparam = false
re_required_modport = false
re_required_module_ansi = false
re_required_module_nonansi = false
re_required_package = false
re_required_parameter = false
re_required_port_inout = false
re_required_port_input = false
re_required_port_interface = false
re_required_port_output = false
re_required_port_ref = false
re_required_program = false
re_required_property = false
re_required_sequence = false
re_required_task = false
re_required_var_class = false
re_required_var_classmethod = false
uppercamelcase_interface = false
uppercamelcase_module = false
uppercamelcase_package = false
style_commaleading = true
style_indent = true
style_keyword_0or1space = false
style_keyword_0space = true
style_keyword_1or2space = false
style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = false
style_keyword_end = true
style_keyword_maybelabel = false
style_keyword_new = false
style_keyword_newline = false
style_operator_arithmetic = false
style_operator_arithmetic_leading_space = false
style_operator_boolean = false
style_operator_boolean_leading_space = false
style_operator_integer = false
style_operator_integer_leading_space = false
style_operator_unary = true
style_trailingwhitespace = true
tab_character = true